### ISSUE TITLE
Token refresh logic bug

### ISSUE THREAD

**Issue by lawrenceakka** [JoDehli/pyloxone-api#5]
I think there is likely a bug in the token_refresh code, but cannot test right now.

Should 
```python 
if key==""
``` 
be

``` python 
if key!=""
```
here:

https://github.com/JoDehli/pyloxone-api/blob/20818d01775c3b204559105577c473f2dcc19cb6/pyloxone_api/api.py#L202-L205

**Comment by JoDehli** [comment]
I also was thinking about how to test it. Maybe we can force a refresh in a separate test after a certain time.

**Comment by lawrenceakka** [comment]
I have fixed this particular bug, but there is still a problem with token refresh. If a message comes in whilst the token is being refreshed, an error  will be generated. I think this is because the mini server does not always send a response to command immediately after receiving it. So a message can come in, between us sending a request for token refresh, and the reply. The  message is then interpreted as the reply, which breaks things. 

Probably most of the token refresh code needs to be moved into the main loop ...

**Comment by JoDehli** [comment]
@lawrenceakka 
Hey Lawrence how are you? Do you think we should implement the pyloxone-api in the next pyloxone version? Or do you think we first should try to fix the token refresh bug? I was looking in the code of pyloxone-api but I first must really study it because it completely changed from my old code. Which was really bad I know :-)

**Comment by machinekoder** [comment]
I'm curious about the status of the project, as I'm planning to make a dashboard. Is `pyloxone-api` ready to use?

**Comment by JoDehli** [comment]
I completely rewrote the API part and this repo and this repo is not under active development. I integrated the API part directly in pyloxone because I had trouble with the dependencies. This repo still has some bugs.
